##This should detect and install missing packages before loading them – hopefully!
list.of.packages <- c("ACD",
"BH",
"colorspace",
"corrplot",
"curl",
"data.table",
"digest",
"dplyr",
"evaluate",
"feather",
"formatR",
"ggplot2",
"grid",
"httr",
"igraph",
"jsonlite",
"knitr",
"lsmeans",
"magrittr",
"mapproj",
"maps",
"OpenNLP",
"outliers",
"pkgconfig",
"plyr",
"plumber",
"RPostgreSQL",
"randomforest",
"RankCluster",
"RColorBrewer",
"Rcpp",
"regtest",
"reshape2",
"tidyr",
"rjson",
"rlang",
"rmarkdown",
"rminer",
"mongolite",
"scales",
"shiny",
"sigclust",
"sqldf",
"stringi",
"stringr",
"survival",
"tibble",
"timeROC",
"tm",
"xml",
"xml2")

new.packages <- list.of.packages[!(list.of.packages
%in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")
lapply(list.of.packages,function(x){library(x,character.only=TRUE)})

